version: '3'
services:
 zookeeper:
  image: confluentinc/cp-zookeeper:7.4.4
  environment:
   ZOOKEEPER_CLIENT_PORT: 2181
   ZOOKEEPER_TICK_TIME: 2000
  ports:
   - 2181:2181

 kafka:
  image: confluentinc/cp-kafka:7.4.4
  depends_on:
   - zookeeper
  ports:
   - 9092:9092
  environment:
   KAFKA_BROKER_ID: 1
   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
   KAFKA_LISTENERS: PLAINTEXT://:9092
   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
   KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

 mysql:
  image: mysql:8.3.0
  container_name: mysql-8.3.0
  restart: always
  environment:
   MYSQL_USER: test
   MYSQL_ROOT_USER: root
   MYSQL_PASSWORD: 'root'
   MYSQL_ROOT_PASSWORD: 'root'
  ports:
   - '3306:3306'
  expose:
   - '3306'
  volumes:
   - mysql-db:/var/lib/mysql

 user-service:
  image: expense-user-service
  container_name: expense-user-service
  ports:
   - '9810:9810'
  depends_on:
   - kafka
   - mysql

 auth-service:
  image: expense-auth-service
  container_name: expense-auth-service
  ports:
   - '9898:9898'
  depends_on:
   - kafka
   - mysql

 kong:
  image: kong
  volumes:
   - "./config:/usr/local/kong/declarative"
  environment:
   KONG_DATABASE: off
   KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
   KONG_PROXY_ACCESS_LOG: /dev/stdout
   KONG_ADMIN_ACCESS_LOG: /dev/stdout
   KONG_PROXY_ERROR_LOG: /dev/stderr
   KONG_ADMIN_ERROR_LOG: /dev/stderr
   KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
   KONG_LOG_LEVEL: debug
   KONG_PLUGINS: bundled
  depends_on:
   - auth-service
   - user-service
  ports:
   - "8005:8000/tcp"
   - "127.0.0.1:7990:8001/tcp"
   - "8443:8443/tcp"
   - "127.0.0.1:8444:8444/tcp"


volumes:
 mysql-db:
  driver: local

#kong.yml
#
#version: '3.3'
#
#services:
#kong:
#image: kong
#volumes:
#- "./config:/usr/local/kong/declarative"
#environment:
#KONG_DATABASE: off
#KONG_DECLARATIVE_CONFIG:
#/usr/local/kong/declarative/kong.yml
#KONG_PROXY_ACCESS_LOG: /dev/stdout
#KONG_ADMIN_ACCESS_LOG: /dev/stdout
#KONG_PROXY_ERROR_LOG: /dev/stderr
#KONG_ADMIN_ERROR_LOG: /dev/stderr
#KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
#KONG_LOG_LEVEL: debug
#KONG_PLUGINS: bundled
#ports:
#- "8005:8000/tcp"
#- "127.0.0.1:7990:8001/tcp"
#- "8443:8443/tcp"
#- "127.0.0.1:8444:8444/tcp"

#config/kong.yml
#
#_format_version: "2.1"
#
#services:
#- name: auth-service
#url: http://172.20.0.5:9898
#routes:
#- name: sign-up
#paths:
#- /auth/v1/signup
#
#- name: user-service
#url: http://172.20.0.6:9810
#routes:
#- name: get-user
#paths:
#- /user/v1/getUser
