_format_version: "2.1"

services:
- name: expense-auth-service
  url: http://172.20.0.5:9898
  routes:
  - name: sign-up
    paths:
    - /auth/v1/signup

- name: expense-user-service
  url: http://172.20.0.6:9810
  routes:
  - name: get-user
    paths:
    - /user/v1/getUser
